---
- name: create health user
  user:
    name: health
    createhome: no
    shell: /usr/sbin/nologin

- name: "create prometheus-node service"
  template:
    src: prometheus-node.j2
    dest: "/etc/systemd/system/prometheus-node.service"
  register: prometheus_node_service

- name: create prometheus dirs
  file:
    path: "/opt/prometheus-node"
    state: directory
    mode: 0775
    owner: health
    group: health

- name: download prometheus-node
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/{{ exporter_version | default('v0.18.1') }}/node_exporter-0.18.1.linux-amd64.tar.gz"
    dest: "/opt/prometheus-node.tar.gz"
  register: prometheus_node_downloaded

- name: untar prometheus-node
  unarchive:
    src: "/opt/prometheus-node.tar.gz"
    remote_src: yes
    dest: "/opt/prometheus-node"
    extra_opts: [--strip-components=1]
    owner: health
    group: health
  when: prometheus_node_downloaded is changed

- name: "systemctl daemon reload"
  shell: "systemctl daemon-reload"
  when: prometheus_node_service.changed
  notify: "reload prometheus-node"

- name: ensure prometheus-node started
  service: 
      name: prometheus-node
      state: started
      enabled: yes